package pers.qyj.graduationpr.mapper;

import java.util.List;
import pers.qyj.graduationpr.pojo.Bedtype;
import pers.qyj.graduationpr.pojo.BedtypeExample;

public interface BedtypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bedtype
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bedtype
     *
     * @mbg.generated
     */
    int insert(Bedtype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bedtype
     *
     * @mbg.generated
     */
    int insertSelective(Bedtype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bedtype
     *
     * @mbg.generated
     */
    List<Bedtype> selectByExample(BedtypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bedtype
     *
     * @mbg.generated
     */
    Bedtype selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bedtype
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Bedtype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bedtype
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Bedtype record);
}