package pers.qyj.graduationpr.mapper;

import java.util.List;
import pers.qyj.graduationpr.pojo.Breakfast;
import pers.qyj.graduationpr.pojo.BreakfastExample;

public interface BreakfastMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table breakfast
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table breakfast
     *
     * @mbg.generated
     */
    int insert(Breakfast record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table breakfast
     *
     * @mbg.generated
     */
    int insertSelective(Breakfast record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table breakfast
     *
     * @mbg.generated
     */
    List<Breakfast> selectByExample(BreakfastExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table breakfast
     *
     * @mbg.generated
     */
    Breakfast selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table breakfast
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Breakfast record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table breakfast
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Breakfast record);
}