package pers.qyj.graduationpr.mapper;

import java.util.List;
import pers.qyj.graduationpr.pojo.Policy;
import pers.qyj.graduationpr.pojo.PolicyExample;

public interface PolicyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table policy
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table policy
     *
     * @mbg.generated
     */
    int insert(Policy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table policy
     *
     * @mbg.generated
     */
    int insertSelective(Policy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table policy
     *
     * @mbg.generated
     */
    List<Policy> selectByExample(PolicyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table policy
     *
     * @mbg.generated
     */
    Policy selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table policy
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Policy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table policy
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Policy record);
}