package pers.qyj.graduationpr.mapper;

import java.util.List;
import pers.qyj.graduationpr.pojo.ResourceFacility;
import pers.qyj.graduationpr.pojo.ResourceFacilityExample;

public interface ResourceFacilityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_facility
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_facility
     *
     * @mbg.generated
     */
    int insert(ResourceFacility record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_facility
     *
     * @mbg.generated
     */
    int insertSelective(ResourceFacility record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_facility
     *
     * @mbg.generated
     */
    List<ResourceFacility> selectByExample(ResourceFacilityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_facility
     *
     * @mbg.generated
     */
    ResourceFacility selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_facility
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ResourceFacility record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_facility
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ResourceFacility record);
}