package pers.qyj.graduationpr.mapper;

import java.util.List;
import pers.qyj.graduationpr.pojo.ResourcePolicy;
import pers.qyj.graduationpr.pojo.ResourcePolicyExample;

public interface ResourcePolicyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_policy
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_policy
     *
     * @mbg.generated
     */
    int insert(ResourcePolicy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_policy
     *
     * @mbg.generated
     */
    int insertSelective(ResourcePolicy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_policy
     *
     * @mbg.generated
     */
    List<ResourcePolicy> selectByExample(ResourcePolicyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_policy
     *
     * @mbg.generated
     */
    ResourcePolicy selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_policy
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ResourcePolicy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_policy
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ResourcePolicy record);
}