package pers.qyj.graduationpr.mapper;

import java.util.List;
import pers.qyj.graduationpr.pojo.ResourceOrder;
import pers.qyj.graduationpr.pojo.ResourceOrderExample;

public interface ResourceOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_order
     *
     * @mbg.generated
     */
    int insert(ResourceOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_order
     *
     * @mbg.generated
     */
    int insertSelective(ResourceOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_order
     *
     * @mbg.generated
     */
    List<ResourceOrder> selectByExample(ResourceOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_order
     *
     * @mbg.generated
     */
    ResourceOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ResourceOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ResourceOrder record);
}