package pers.qyj.graduationpr.mapper;

import java.util.List;
import pers.qyj.graduationpr.pojo.ResourceSign;
import pers.qyj.graduationpr.pojo.ResourceSignExample;

public interface ResourceSignMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_sign
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String sign);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_sign
     *
     * @mbg.generated
     */
    int insert(ResourceSign record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_sign
     *
     * @mbg.generated
     */
    int insertSelective(ResourceSign record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_sign
     *
     * @mbg.generated
     */
    List<ResourceSign> selectByExample(ResourceSignExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_sign
     *
     * @mbg.generated
     */
    ResourceSign selectByPrimaryKey(String sign);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_sign
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ResourceSign record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_sign
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ResourceSign record);
}