package pers.qyj.graduationpr.mapper;

import java.util.List;
import pers.qyj.graduationpr.pojo.SignUser;
import pers.qyj.graduationpr.pojo.SignUserExample;

public interface SignUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_user
     *
     * @mbg.generated
     */
    int insert(SignUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_user
     *
     * @mbg.generated
     */
    int insertSelective(SignUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_user
     *
     * @mbg.generated
     */
    List<SignUser> selectByExample(SignUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_user
     *
     * @mbg.generated
     */
    SignUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SignUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SignUser record);
}