package pers.qyj.graduationpr.mapper;

import java.util.List;
import pers.qyj.graduationpr.pojo.SystemConfiguration;
import pers.qyj.graduationpr.pojo.SystemConfigurationExample;

public interface SystemConfigurationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_configuration
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_configuration
     *
     * @mbg.generated
     */
    int insert(SystemConfiguration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_configuration
     *
     * @mbg.generated
     */
    int insertSelective(SystemConfiguration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_configuration
     *
     * @mbg.generated
     */
    List<SystemConfiguration> selectByExample(SystemConfigurationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_configuration
     *
     * @mbg.generated
     */
    SystemConfiguration selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_configuration
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SystemConfiguration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_configuration
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SystemConfiguration record);
}