package pers.qyj.graduationpr.mapper;

import java.util.List;
import pers.qyj.graduationpr.pojo.Userinformation;
import pers.qyj.graduationpr.pojo.UserinformationExample;

public interface UserinformationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinformation
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinformation
     *
     * @mbg.generated
     */
    int insert(Userinformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinformation
     *
     * @mbg.generated
     */
    int insertSelective(Userinformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinformation
     *
     * @mbg.generated
     */
    List<Userinformation> selectByExample(UserinformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinformation
     *
     * @mbg.generated
     */
    Userinformation selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinformation
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Userinformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinformation
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Userinformation record);
}