package pers.qyj.graduationpr.pojo;

import java.util.Date;

public class Sign {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column signs.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column signs.sign
     *
     * @mbg.generated
     */
    private String sign;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column signs.oid
     *
     * @mbg.generated
     */
    private Integer oid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column signs.reid
     *
     * @mbg.generated
     */
    private Integer reid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column signs.arrival_date
     *
     * @mbg.generated
     */
    private Date arrivalDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column signs.depature_date
     *
     * @mbg.generated
     */
    private Date depatureDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column signs.number
     *
     * @mbg.generated
     */
    private Integer number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column signs.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column signs.id
     *
     * @return the value of signs.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column signs.id
     *
     * @param id the value for signs.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column signs.sign
     *
     * @return the value of signs.sign
     *
     * @mbg.generated
     */
    public String getSign() {
        return sign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column signs.sign
     *
     * @param sign the value for signs.sign
     *
     * @mbg.generated
     */
    public void setSign(String sign) {
        this.sign = sign == null ? null : sign.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column signs.oid
     *
     * @return the value of signs.oid
     *
     * @mbg.generated
     */
    public Integer getOid() {
        return oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column signs.oid
     *
     * @param oid the value for signs.oid
     *
     * @mbg.generated
     */
    public void setOid(Integer oid) {
        this.oid = oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column signs.reid
     *
     * @return the value of signs.reid
     *
     * @mbg.generated
     */
    public Integer getReid() {
        return reid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column signs.reid
     *
     * @param reid the value for signs.reid
     *
     * @mbg.generated
     */
    public void setReid(Integer reid) {
        this.reid = reid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column signs.arrival_date
     *
     * @return the value of signs.arrival_date
     *
     * @mbg.generated
     */
    public Date getArrivalDate() {
        return arrivalDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column signs.arrival_date
     *
     * @param arrivalDate the value for signs.arrival_date
     *
     * @mbg.generated
     */
    public void setArrivalDate(Date arrivalDate) {
        this.arrivalDate = arrivalDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column signs.depature_date
     *
     * @return the value of signs.depature_date
     *
     * @mbg.generated
     */
    public Date getDepatureDate() {
        return depatureDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column signs.depature_date
     *
     * @param depatureDate the value for signs.depature_date
     *
     * @mbg.generated
     */
    public void setDepatureDate(Date depatureDate) {
        this.depatureDate = depatureDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column signs.number
     *
     * @return the value of signs.number
     *
     * @mbg.generated
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column signs.number
     *
     * @param number the value for signs.number
     *
     * @mbg.generated
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column signs.status
     *
     * @return the value of signs.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column signs.status
     *
     * @param status the value for signs.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}