package pers.qyj.graduationpr.pojo;

import java.util.Date;

public class Order {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.sign
     *
     * @mbg.generated
     */
    private String sign;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.trade_status
     *
     * @mbg.generated
     */
    private Integer tradeStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.pay_status
     *
     * @mbg.generated
     */
    private Integer payStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.user_name
     *
     * @mbg.generated
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.user_phone
     *
     * @mbg.generated
     */
    private String userPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.user_email
     *
     * @mbg.generated
     */
    private String userEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.partiality
     *
     * @mbg.generated
     */
    private String partiality;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.invoice_type
     *
     * @mbg.generated
     */
    private Integer invoiceType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.invoice_group
     *
     * @mbg.generated
     */
    private Integer invoiceGroup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.invoice_title
     *
     * @mbg.generated
     */
    private String invoiceTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.payment
     *
     * @mbg.generated
     */
    private Integer payment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.date
     *
     * @mbg.generated
     */
    private Date date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.id
     *
     * @return the value of orders.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.id
     *
     * @param id the value for orders.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.sign
     *
     * @return the value of orders.sign
     *
     * @mbg.generated
     */
    public String getSign() {
        return sign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.sign
     *
     * @param sign the value for orders.sign
     *
     * @mbg.generated
     */
    public void setSign(String sign) {
        this.sign = sign == null ? null : sign.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.trade_status
     *
     * @return the value of orders.trade_status
     *
     * @mbg.generated
     */
    public Integer getTradeStatus() {
        return tradeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.trade_status
     *
     * @param tradeStatus the value for orders.trade_status
     *
     * @mbg.generated
     */
    public void setTradeStatus(Integer tradeStatus) {
        this.tradeStatus = tradeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.pay_status
     *
     * @return the value of orders.pay_status
     *
     * @mbg.generated
     */
    public Integer getPayStatus() {
        return payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.pay_status
     *
     * @param payStatus the value for orders.pay_status
     *
     * @mbg.generated
     */
    public void setPayStatus(Integer payStatus) {
        this.payStatus = payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.user_name
     *
     * @return the value of orders.user_name
     *
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.user_name
     *
     * @param userName the value for orders.user_name
     *
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.user_phone
     *
     * @return the value of orders.user_phone
     *
     * @mbg.generated
     */
    public String getUserPhone() {
        return userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.user_phone
     *
     * @param userPhone the value for orders.user_phone
     *
     * @mbg.generated
     */
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone == null ? null : userPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.user_email
     *
     * @return the value of orders.user_email
     *
     * @mbg.generated
     */
    public String getUserEmail() {
        return userEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.user_email
     *
     * @param userEmail the value for orders.user_email
     *
     * @mbg.generated
     */
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail == null ? null : userEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.partiality
     *
     * @return the value of orders.partiality
     *
     * @mbg.generated
     */
    public String getPartiality() {
        return partiality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.partiality
     *
     * @param partiality the value for orders.partiality
     *
     * @mbg.generated
     */
    public void setPartiality(String partiality) {
        this.partiality = partiality == null ? null : partiality.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.invoice_type
     *
     * @return the value of orders.invoice_type
     *
     * @mbg.generated
     */
    public Integer getInvoiceType() {
        return invoiceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.invoice_type
     *
     * @param invoiceType the value for orders.invoice_type
     *
     * @mbg.generated
     */
    public void setInvoiceType(Integer invoiceType) {
        this.invoiceType = invoiceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.invoice_group
     *
     * @return the value of orders.invoice_group
     *
     * @mbg.generated
     */
    public Integer getInvoiceGroup() {
        return invoiceGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.invoice_group
     *
     * @param invoiceGroup the value for orders.invoice_group
     *
     * @mbg.generated
     */
    public void setInvoiceGroup(Integer invoiceGroup) {
        this.invoiceGroup = invoiceGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.invoice_title
     *
     * @return the value of orders.invoice_title
     *
     * @mbg.generated
     */
    public String getInvoiceTitle() {
        return invoiceTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.invoice_title
     *
     * @param invoiceTitle the value for orders.invoice_title
     *
     * @mbg.generated
     */
    public void setInvoiceTitle(String invoiceTitle) {
        this.invoiceTitle = invoiceTitle == null ? null : invoiceTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.payment
     *
     * @return the value of orders.payment
     *
     * @mbg.generated
     */
    public Integer getPayment() {
        return payment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.payment
     *
     * @param payment the value for orders.payment
     *
     * @mbg.generated
     */
    public void setPayment(Integer payment) {
        this.payment = payment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.date
     *
     * @return the value of orders.date
     *
     * @mbg.generated
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.date
     *
     * @param date the value for orders.date
     *
     * @mbg.generated
     */
    public void setDate(Date date) {
        this.date = date;
    }
}