package pers.qyj.graduationpr.pojo;

public class ResourcePolicy {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_policy.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_policy.reid
     *
     * @mbg.generated
     */
    private Integer reid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_policy.poid
     *
     * @mbg.generated
     */
    private Integer poid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_policy.id
     *
     * @return the value of resource_policy.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_policy.id
     *
     * @param id the value for resource_policy.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_policy.reid
     *
     * @return the value of resource_policy.reid
     *
     * @mbg.generated
     */
    public Integer getReid() {
        return reid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_policy.reid
     *
     * @param reid the value for resource_policy.reid
     *
     * @mbg.generated
     */
    public void setReid(Integer reid) {
        this.reid = reid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_policy.poid
     *
     * @return the value of resource_policy.poid
     *
     * @mbg.generated
     */
    public Integer getPoid() {
        return poid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_policy.poid
     *
     * @param poid the value for resource_policy.poid
     *
     * @mbg.generated
     */
    public void setPoid(Integer poid) {
        this.poid = poid;
    }
}