package pers.qyj.graduationpr.pojo;

public class ResourceSign {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_sign.sign
     *
     * @mbg.generated
     */
    private String sign;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_sign.reid
     *
     * @mbg.generated
     */
    private Integer reid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_sign.sign
     *
     * @return the value of resource_sign.sign
     *
     * @mbg.generated
     */
    public String getSign() {
        return sign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_sign.sign
     *
     * @param sign the value for resource_sign.sign
     *
     * @mbg.generated
     */
    public void setSign(String sign) {
        this.sign = sign == null ? null : sign.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_sign.reid
     *
     * @return the value of resource_sign.reid
     *
     * @mbg.generated
     */
    public Integer getReid() {
        return reid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_sign.reid
     *
     * @param reid the value for resource_sign.reid
     *
     * @mbg.generated
     */
    public void setReid(Integer reid) {
        this.reid = reid;
    }
}