package pers.qyj.graduationpr.pojo;

public class Resource {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.sign
     *
     * @mbg.generated
     */
    private String sign;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.roomtype
     *
     * @mbg.generated
     */
    private String roomtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.breakfast
     *
     * @mbg.generated
     */
    private String breakfast;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.price
     *
     * @mbg.generated
     */
    private Integer price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.remain
     *
     * @mbg.generated
     */
    private Integer remain;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.desc_
     *
     * @mbg.generated
     */
    private String desc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.id
     *
     * @return the value of resource.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.id
     *
     * @param id the value for resource.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.sign
     *
     * @return the value of resource.sign
     *
     * @mbg.generated
     */
    public String getSign() {
        return sign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.sign
     *
     * @param sign the value for resource.sign
     *
     * @mbg.generated
     */
    public void setSign(String sign) {
        this.sign = sign == null ? null : sign.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.roomtype
     *
     * @return the value of resource.roomtype
     *
     * @mbg.generated
     */
    public String getRoomtype() {
        return roomtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.roomtype
     *
     * @param roomtype the value for resource.roomtype
     *
     * @mbg.generated
     */
    public void setRoomtype(String roomtype) {
        this.roomtype = roomtype == null ? null : roomtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.breakfast
     *
     * @return the value of resource.breakfast
     *
     * @mbg.generated
     */
    public String getBreakfast() {
        return breakfast;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.breakfast
     *
     * @param breakfast the value for resource.breakfast
     *
     * @mbg.generated
     */
    public void setBreakfast(String breakfast) {
        this.breakfast = breakfast == null ? null : breakfast.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.price
     *
     * @return the value of resource.price
     *
     * @mbg.generated
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.price
     *
     * @param price the value for resource.price
     *
     * @mbg.generated
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.remain
     *
     * @return the value of resource.remain
     *
     * @mbg.generated
     */
    public Integer getRemain() {
        return remain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.remain
     *
     * @param remain the value for resource.remain
     *
     * @mbg.generated
     */
    public void setRemain(Integer remain) {
        this.remain = remain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.desc_
     *
     * @return the value of resource.desc_
     *
     * @mbg.generated
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.desc_
     *
     * @param desc the value for resource.desc_
     *
     * @mbg.generated
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.status
     *
     * @return the value of resource.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.status
     *
     * @param status the value for resource.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}