package pers.qyj.graduationpr.pojo;

public class ResourceFacility {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_facility.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_facility.reid
     *
     * @mbg.generated
     */
    private Integer reid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_facility.fid
     *
     * @mbg.generated
     */
    private Integer fid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_facility.id
     *
     * @return the value of resource_facility.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_facility.id
     *
     * @param id the value for resource_facility.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_facility.reid
     *
     * @return the value of resource_facility.reid
     *
     * @mbg.generated
     */
    public Integer getReid() {
        return reid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_facility.reid
     *
     * @param reid the value for resource_facility.reid
     *
     * @mbg.generated
     */
    public void setReid(Integer reid) {
        this.reid = reid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_facility.fid
     *
     * @return the value of resource_facility.fid
     *
     * @mbg.generated
     */
    public Integer getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_facility.fid
     *
     * @param fid the value for resource_facility.fid
     *
     * @mbg.generated
     */
    public void setFid(Integer fid) {
        this.fid = fid;
    }
}