package pers.qyj.graduationpr.pojo;

public class ResourceOrder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_order.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_order.oid
     *
     * @mbg.generated
     */
    private Integer oid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_order.reid
     *
     * @mbg.generated
     */
    private Integer reid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_order.number
     *
     * @mbg.generated
     */
    private Integer number;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_order.id
     *
     * @return the value of resource_order.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_order.id
     *
     * @param id the value for resource_order.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_order.oid
     *
     * @return the value of resource_order.oid
     *
     * @mbg.generated
     */
    public Integer getOid() {
        return oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_order.oid
     *
     * @param oid the value for resource_order.oid
     *
     * @mbg.generated
     */
    public void setOid(Integer oid) {
        this.oid = oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_order.reid
     *
     * @return the value of resource_order.reid
     *
     * @mbg.generated
     */
    public Integer getReid() {
        return reid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_order.reid
     *
     * @param reid the value for resource_order.reid
     *
     * @mbg.generated
     */
    public void setReid(Integer reid) {
        this.reid = reid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_order.number
     *
     * @return the value of resource_order.number
     *
     * @mbg.generated
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_order.number
     *
     * @param number the value for resource_order.number
     *
     * @mbg.generated
     */
    public void setNumber(Integer number) {
        this.number = number;
    }
}