package pers.qyj.graduationpr.pojo;

public class Roomtype {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roomtype.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roomtype.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roomtype.bedtype
     *
     * @mbg.generated
     */
    private String bedtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roomtype.people
     *
     * @mbg.generated
     */
    private Integer people;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roomtype.size
     *
     * @mbg.generated
     */
    private String size;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roomtype.price
     *
     * @mbg.generated
     */
    private Integer price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roomtype.imgurl
     *
     * @mbg.generated
     */
    private String imgurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roomtype.desc_
     *
     * @mbg.generated
     */
    private String desc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roomtype.id
     *
     * @return the value of roomtype.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roomtype.id
     *
     * @param id the value for roomtype.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roomtype.name
     *
     * @return the value of roomtype.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roomtype.name
     *
     * @param name the value for roomtype.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roomtype.bedtype
     *
     * @return the value of roomtype.bedtype
     *
     * @mbg.generated
     */
    public String getBedtype() {
        return bedtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roomtype.bedtype
     *
     * @param bedtype the value for roomtype.bedtype
     *
     * @mbg.generated
     */
    public void setBedtype(String bedtype) {
        this.bedtype = bedtype == null ? null : bedtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roomtype.people
     *
     * @return the value of roomtype.people
     *
     * @mbg.generated
     */
    public Integer getPeople() {
        return people;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roomtype.people
     *
     * @param people the value for roomtype.people
     *
     * @mbg.generated
     */
    public void setPeople(Integer people) {
        this.people = people;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roomtype.size
     *
     * @return the value of roomtype.size
     *
     * @mbg.generated
     */
    public String getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roomtype.size
     *
     * @param size the value for roomtype.size
     *
     * @mbg.generated
     */
    public void setSize(String size) {
        this.size = size == null ? null : size.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roomtype.price
     *
     * @return the value of roomtype.price
     *
     * @mbg.generated
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roomtype.price
     *
     * @param price the value for roomtype.price
     *
     * @mbg.generated
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roomtype.imgurl
     *
     * @return the value of roomtype.imgurl
     *
     * @mbg.generated
     */
    public String getImgurl() {
        return imgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roomtype.imgurl
     *
     * @param imgurl the value for roomtype.imgurl
     *
     * @mbg.generated
     */
    public void setImgurl(String imgurl) {
        this.imgurl = imgurl == null ? null : imgurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roomtype.desc_
     *
     * @return the value of roomtype.desc_
     *
     * @mbg.generated
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roomtype.desc_
     *
     * @param desc the value for roomtype.desc_
     *
     * @mbg.generated
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }
}