package pers.qyj.graduationpr.pojo;

import java.util.ArrayList;
import java.util.List;

public class SignUserExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sign_user
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sign_user
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sign_user
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_user
     *
     * @mbg.generated
     */
    public SignUserExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_user
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_user
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_user
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_user
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_user
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_user
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_user
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_user
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_user
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_user
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sign_user
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSignIsNull() {
            addCriterion("sign is null");
            return (Criteria) this;
        }

        public Criteria andSignIsNotNull() {
            addCriterion("sign is not null");
            return (Criteria) this;
        }

        public Criteria andSignEqualTo(String value) {
            addCriterion("sign =", value, "sign");
            return (Criteria) this;
        }

        public Criteria andSignNotEqualTo(String value) {
            addCriterion("sign <>", value, "sign");
            return (Criteria) this;
        }

        public Criteria andSignGreaterThan(String value) {
            addCriterion("sign >", value, "sign");
            return (Criteria) this;
        }

        public Criteria andSignGreaterThanOrEqualTo(String value) {
            addCriterion("sign >=", value, "sign");
            return (Criteria) this;
        }

        public Criteria andSignLessThan(String value) {
            addCriterion("sign <", value, "sign");
            return (Criteria) this;
        }

        public Criteria andSignLessThanOrEqualTo(String value) {
            addCriterion("sign <=", value, "sign");
            return (Criteria) this;
        }

        public Criteria andSignLike(String value) {
            addCriterion("sign like", value, "sign");
            return (Criteria) this;
        }

        public Criteria andSignNotLike(String value) {
            addCriterion("sign not like", value, "sign");
            return (Criteria) this;
        }

        public Criteria andSignIn(List<String> values) {
            addCriterion("sign in", values, "sign");
            return (Criteria) this;
        }

        public Criteria andSignNotIn(List<String> values) {
            addCriterion("sign not in", values, "sign");
            return (Criteria) this;
        }

        public Criteria andSignBetween(String value1, String value2) {
            addCriterion("sign between", value1, value2, "sign");
            return (Criteria) this;
        }

        public Criteria andSignNotBetween(String value1, String value2) {
            addCriterion("sign not between", value1, value2, "sign");
            return (Criteria) this;
        }

        public Criteria andUserLastnameIsNull() {
            addCriterion("user_lastname is null");
            return (Criteria) this;
        }

        public Criteria andUserLastnameIsNotNull() {
            addCriterion("user_lastname is not null");
            return (Criteria) this;
        }

        public Criteria andUserLastnameEqualTo(String value) {
            addCriterion("user_lastname =", value, "userLastname");
            return (Criteria) this;
        }

        public Criteria andUserLastnameNotEqualTo(String value) {
            addCriterion("user_lastname <>", value, "userLastname");
            return (Criteria) this;
        }

        public Criteria andUserLastnameGreaterThan(String value) {
            addCriterion("user_lastname >", value, "userLastname");
            return (Criteria) this;
        }

        public Criteria andUserLastnameGreaterThanOrEqualTo(String value) {
            addCriterion("user_lastname >=", value, "userLastname");
            return (Criteria) this;
        }

        public Criteria andUserLastnameLessThan(String value) {
            addCriterion("user_lastname <", value, "userLastname");
            return (Criteria) this;
        }

        public Criteria andUserLastnameLessThanOrEqualTo(String value) {
            addCriterion("user_lastname <=", value, "userLastname");
            return (Criteria) this;
        }

        public Criteria andUserLastnameLike(String value) {
            addCriterion("user_lastname like", value, "userLastname");
            return (Criteria) this;
        }

        public Criteria andUserLastnameNotLike(String value) {
            addCriterion("user_lastname not like", value, "userLastname");
            return (Criteria) this;
        }

        public Criteria andUserLastnameIn(List<String> values) {
            addCriterion("user_lastname in", values, "userLastname");
            return (Criteria) this;
        }

        public Criteria andUserLastnameNotIn(List<String> values) {
            addCriterion("user_lastname not in", values, "userLastname");
            return (Criteria) this;
        }

        public Criteria andUserLastnameBetween(String value1, String value2) {
            addCriterion("user_lastname between", value1, value2, "userLastname");
            return (Criteria) this;
        }

        public Criteria andUserLastnameNotBetween(String value1, String value2) {
            addCriterion("user_lastname not between", value1, value2, "userLastname");
            return (Criteria) this;
        }

        public Criteria andUserFirstnameIsNull() {
            addCriterion("user_firstname is null");
            return (Criteria) this;
        }

        public Criteria andUserFirstnameIsNotNull() {
            addCriterion("user_firstname is not null");
            return (Criteria) this;
        }

        public Criteria andUserFirstnameEqualTo(String value) {
            addCriterion("user_firstname =", value, "userFirstname");
            return (Criteria) this;
        }

        public Criteria andUserFirstnameNotEqualTo(String value) {
            addCriterion("user_firstname <>", value, "userFirstname");
            return (Criteria) this;
        }

        public Criteria andUserFirstnameGreaterThan(String value) {
            addCriterion("user_firstname >", value, "userFirstname");
            return (Criteria) this;
        }

        public Criteria andUserFirstnameGreaterThanOrEqualTo(String value) {
            addCriterion("user_firstname >=", value, "userFirstname");
            return (Criteria) this;
        }

        public Criteria andUserFirstnameLessThan(String value) {
            addCriterion("user_firstname <", value, "userFirstname");
            return (Criteria) this;
        }

        public Criteria andUserFirstnameLessThanOrEqualTo(String value) {
            addCriterion("user_firstname <=", value, "userFirstname");
            return (Criteria) this;
        }

        public Criteria andUserFirstnameLike(String value) {
            addCriterion("user_firstname like", value, "userFirstname");
            return (Criteria) this;
        }

        public Criteria andUserFirstnameNotLike(String value) {
            addCriterion("user_firstname not like", value, "userFirstname");
            return (Criteria) this;
        }

        public Criteria andUserFirstnameIn(List<String> values) {
            addCriterion("user_firstname in", values, "userFirstname");
            return (Criteria) this;
        }

        public Criteria andUserFirstnameNotIn(List<String> values) {
            addCriterion("user_firstname not in", values, "userFirstname");
            return (Criteria) this;
        }

        public Criteria andUserFirstnameBetween(String value1, String value2) {
            addCriterion("user_firstname between", value1, value2, "userFirstname");
            return (Criteria) this;
        }

        public Criteria andUserFirstnameNotBetween(String value1, String value2) {
            addCriterion("user_firstname not between", value1, value2, "userFirstname");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sign_user
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sign_user
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}