package pers.qyj.graduationpr.pojo;

public class SystemConfiguration {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_configuration.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_configuration.arrival_time
     *
     * @mbg.generated
     */
    private String arrivalTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_configuration.depature_time
     *
     * @mbg.generated
     */
    private String depatureTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_configuration.id
     *
     * @return the value of system_configuration.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_configuration.id
     *
     * @param id the value for system_configuration.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_configuration.arrival_time
     *
     * @return the value of system_configuration.arrival_time
     *
     * @mbg.generated
     */
    public String getArrivalTime() {
        return arrivalTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_configuration.arrival_time
     *
     * @param arrivalTime the value for system_configuration.arrival_time
     *
     * @mbg.generated
     */
    public void setArrivalTime(String arrivalTime) {
        this.arrivalTime = arrivalTime == null ? null : arrivalTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_configuration.depature_time
     *
     * @return the value of system_configuration.depature_time
     *
     * @mbg.generated
     */
    public String getDepatureTime() {
        return depatureTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_configuration.depature_time
     *
     * @param depatureTime the value for system_configuration.depature_time
     *
     * @mbg.generated
     */
    public void setDepatureTime(String depatureTime) {
        this.depatureTime = depatureTime == null ? null : depatureTime.trim();
    }
}