package pers.qyj.graduationpr.pojo;

public class Userinformation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinformation.ID
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinformation.HEAD_PORTRAIT
     *
     * @mbg.generated
     */
    private String headPortrait;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinformation.NAME
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinformation.BIRTHDAY
     *
     * @mbg.generated
     */
    private String birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinformation.SEX
     *
     * @mbg.generated
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinformation.PHONE
     *
     * @mbg.generated
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinformation.PREFECTURE
     *
     * @mbg.generated
     */
    private String prefecture;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinformation.REAL_NAME
     *
     * @mbg.generated
     */
    private String realName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinformation.ID_CARD
     *
     * @mbg.generated
     */
    private String idCard;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinformation.ID
     *
     * @return the value of userinformation.ID
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinformation.ID
     *
     * @param id the value for userinformation.ID
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinformation.HEAD_PORTRAIT
     *
     * @return the value of userinformation.HEAD_PORTRAIT
     *
     * @mbg.generated
     */
    public String getHeadPortrait() {
        return headPortrait;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinformation.HEAD_PORTRAIT
     *
     * @param headPortrait the value for userinformation.HEAD_PORTRAIT
     *
     * @mbg.generated
     */
    public void setHeadPortrait(String headPortrait) {
        this.headPortrait = headPortrait == null ? null : headPortrait.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinformation.NAME
     *
     * @return the value of userinformation.NAME
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinformation.NAME
     *
     * @param name the value for userinformation.NAME
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinformation.BIRTHDAY
     *
     * @return the value of userinformation.BIRTHDAY
     *
     * @mbg.generated
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinformation.BIRTHDAY
     *
     * @param birthday the value for userinformation.BIRTHDAY
     *
     * @mbg.generated
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday == null ? null : birthday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinformation.SEX
     *
     * @return the value of userinformation.SEX
     *
     * @mbg.generated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinformation.SEX
     *
     * @param sex the value for userinformation.SEX
     *
     * @mbg.generated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinformation.PHONE
     *
     * @return the value of userinformation.PHONE
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinformation.PHONE
     *
     * @param phone the value for userinformation.PHONE
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinformation.PREFECTURE
     *
     * @return the value of userinformation.PREFECTURE
     *
     * @mbg.generated
     */
    public String getPrefecture() {
        return prefecture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinformation.PREFECTURE
     *
     * @param prefecture the value for userinformation.PREFECTURE
     *
     * @mbg.generated
     */
    public void setPrefecture(String prefecture) {
        this.prefecture = prefecture == null ? null : prefecture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinformation.REAL_NAME
     *
     * @return the value of userinformation.REAL_NAME
     *
     * @mbg.generated
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinformation.REAL_NAME
     *
     * @param realName the value for userinformation.REAL_NAME
     *
     * @mbg.generated
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinformation.ID_CARD
     *
     * @return the value of userinformation.ID_CARD
     *
     * @mbg.generated
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinformation.ID_CARD
     *
     * @param idCard the value for userinformation.ID_CARD
     *
     * @mbg.generated
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard == null ? null : idCard.trim();
    }
}